sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.m2

language: android

#jdk:
#  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    # to find the available build tools version
    # cd $ANDROID_HOME
    # e.g. in /d/android/SDK/tools/bin
    # $ ./sdkmanager.bat --list | grep build
    - build-tools-27.0.3
    - android-27

before_install:
 - chmod +x gradlew

script:
  - ./gradlew clean check assemble
