sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.m2

language: android

#jdk:
#  - oraclejdk8

android:
  components:
    - tools
    - platform-tools

licenses:
  - 'android-.+'
  - 'android-.+'
  - 'intel-android.+'

# another workaround for newer licensing issue
# - https://stackoverflow.com/a/47726910/6287240
# - https://github.com/travis-ci/travis-ci/issues/6555#issuecomment-282635361
before_install:
- yes | sdkmanager "platforms;android-27"
- yes | sdkmanager build-tools-27.1.0
 - chmod +x gradlew

script:
  - ./gradlew clean check assemble
