sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.m2

language: android

#jdk:
#  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
#    - android-27
#    - build-tools-27.1.0

# workaround for new android versions as suggested here:
# https://github.com/travis-ci/docs-travis-ci-com/issues/779#issuecomment-282635354
install:
  - echo y | android update sdk -u -a -t build-tools-27.1.0
  - echo y | android update sdk -u -a -t android-27

before_install:
 - chmod +x gradlew

script:
  - ./gradlew clean check assemble
